application: mediaserver-153018
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /
  script: main.application
- url: /stylesheet\.css
  static_files: stylesheet.css
  upload: stylesheet\.css
  
libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"
